name: S3 deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: Sync S3 bucket
        run: aws s3 sync ./src s3://${{ secrets.S3_BUCKET_NAME }} --delete"
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"